using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//This code has been modified from 1330 Studio's BTD6E Modules. Huge thanks to them for letting me use this code.

namespace minicustomtowers.Resources
{ 
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("minicustomtowers.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Shader
        {
            get
            {
                object obj = ResourceManager.GetObject("Shader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] FlaminShuriken
        {
            get
            {
                object obj = ResourceManager.GetObject("FlaminShuriken", resourceCulture);
                return ((byte[])(obj));
            }
        }
     internal static byte[] SunTerror
        {
            get
            {
                object obj = ResourceManager.GetObject("SunTerror", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] BionicGlaives
        {
            get
            {
                object obj = ResourceManager.GetObject("BionicGlaives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] Bombjitsu
        {
            get
            {
                object obj = ResourceManager.GetObject("Bombjitsu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] Bombjitsu_Portrait
        {
            get
            {
                object obj = ResourceManager.GetObject("Bombjitsu_Portrait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] OperationNevaMiss
        {
            get
            {
                object obj = ResourceManager.GetObject("OperationNevaMiss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] TripleJuggernaut
        {
            get
            {
                object obj = ResourceManager.GetObject("TripleJuggernaut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        internal static byte[] BananaRepublic
        {
            get
            {
                object obj = ResourceManager.GetObject("BananaRepublic", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
